image: registry.gitlab.com/epic_wink/aws-sfn-service/ci

stages:
  - build
  - test
  - release


build-package:
  stage: build
  only:
    - master
    - develop
    - /^v(\d+)\.(\d+)\.(\d+)((a|b|A|B|(rc)|(RC))(\d+))?$/
  script:
    - rm -rf build/*
    - pip3 wheel -w build-wheel/ . --no-deps
    - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - build-wheel/
      - dist/

test-package:
  stage: test
  only:
    - master
    - develop
    - /^v(\d+)\.(\d+)\.(\d+)((a|b|A|B|(rc)|(RC))(\d+))?$/
  dependencies:
    - build-package
  script:
    - pip3 install $(find build-wheel/ -name sfini-*.whl | head -n1)[dev]
    - >
      pytest -vvrxrs
      --cov=/usr/local/lib/python3.6/dist-packages/sfini
      --cov-report=html --cov-report=term
  artifacts:
    paths:
      - htmlcov/

release-package:
  stage: release
  only:
    - /^v(\d+)\.(\d+)\.(\d+)((a|b|A|B|(rc)|(RC))(\d+))?$/
  when: manual
  dependencies:
    - build-package
  script:
    - pip3 install twine
    - twine upload dist/*
